version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "build/ci"
      - "bot"
    commit-message:
      prefix: "ci"
    groups:
      prod-actions:
        dependency-type: "production"
