#
# ObjectifiedElement hierarchy
#

import abc
import sys
from collections.abc import (
    Callable,
    Iterable,
    Iterator,
)
from typing import (
    Any,
    Literal,
    overload,
)
from typing_extensions import SupportsIndex

from .._types import (
    _CSSTransArg,
    _TagName,
    _TextArg,
)
from ..etree import CDATA, ElementBase

if sys.version_info >= (3, 11):
    from typing import LiteralString, Self
else:
    from typing_extensions import LiteralString, Self

class ObjectifiedElement(ElementBase):
    """Element class that provides object-like access to XML elements.

    Element children are accessed as object attributes.  Multiple children
    with the same name are available through a list index.

    See Also
    --------
    - [API Documentation](https://lxml.de/apidoc/lxml.objectify.html#lxml.objectify.ObjectifiedElement)
    """

    # Readonly, unlike _Element counterpart
    @property  # type: ignore[misc]
    # pyrefly: ignore[bad-override]
    def text(  # pyright: ignore[reportIncompatibleMethodOverride]
        self,
    ) -> str | None: ...
    # addattr() is like __setattr__ but always adds DataElement,
    # while __setattr__ has some safety checks and may replace
    # existing elements. Value can be any object, it is converted
    # to DataElement on-the-fly whenever supported.
    def addattr(self, tag: _TagName, value: object) -> None: ...
    def countchildren(self) -> int: ...
    def descendantpaths(self, prefix: str | list[str] | None = None) -> list[str]: ...
    def getchildren(  # pyright: ignore[reportIncompatibleMethodOverride]  # ty: ignore[invalid-method-override]
        self,
    ) -> list[ObjectifiedElement]: ...
    def __iter__(self) -> Iterator[ObjectifiedElement]: ...
    def __reversed__(self) -> Iterator[ObjectifiedElement]: ...
    def __getattr__(self, __name: str) -> ObjectifiedElement: ...
    # See addattr() above
    def __setattr__(self, __name: str, __value: object) -> None: ...
    def __delattr__(self, __name: str) -> None: ...
    # elem['foo'] is equivalent to elem.foo, but allows for
    # special attribute names (like 'text' or 'tail')
    @overload
    def __getitem__(self, key: int | str | bytes, /) -> ObjectifiedElement: ...
    @overload
    def __getitem__(  # pyright: ignore[reportIncompatibleMethodOverride]  # ty: ignore[invalid-method-override]
        self,
        key: slice,
        /,
    ) -> list[ObjectifiedElement]: ...
    @overload
    def __setitem__(self, key: int | str | bytes, value: object, /) -> None: ...
    @overload
    def __setitem__(self, key: slice, value: Iterable[object], /) -> None: ...
    def __delitem__(self, key: int | slice, /) -> None: ...
    # TODO Check if _Element methods need overriding
    # CSS selector is not a normal use case for objectified
    # element (and unnecessary), but still usable nonetheless
    def cssselect(  # pyright: ignore[reportIncompatibleMethodOverride]  # ty: ignore[invalid-method-override]
        self,
        expr: str,
        *,
        translator: _CSSTransArg = "xml",
    ) -> list[ObjectifiedElement]: ...

class ObjectifiedDataElement(ObjectifiedElement):
    """The base class for all data type Elements.

    Subclasses should override the `.pyval` property and possibly
    the `__str__` method.

    See Also
    --------
    - [API Documentation](https://lxml.de/apidoc/lxml.objectify.html#lxml.objectify.ObjectifiedDataElement)
    """

    # In source code, .pyval return value is stated as str. However,
    # presence of the attribute is supposed to be protocol requirement
    # for subclasses, not that people are allowed to create
    # ObjectifiedDataElement themselves which return string value for .pyval .
    @property
    @abc.abstractmethod
    def pyval(self) -> Any: ...
    def _setText(self, s: _TextArg | CDATA | None) -> None:
        """Modify text content of objectified element directly.

        For use in subclasses only. Don't use unless you know what you are doing.

        See Also
        --------
        - [API Documentation](https://lxml.de/apidoc/lxml.objectify.html#lxml.objectify.ObjectifiedDataElement._setText)
        """

# NOT marking as disjoint_base
class NumberElement(ObjectifiedDataElement, metaclass=abc.ABCMeta):
    @property  # type: ignore[misc]
    def text(self) -> str: ...
    def _setValueParser(self, function: Callable[[str], Any]) -> None:
        """Set the function that parses the Python value from a string

        See Also
        --------
        - [API Documentation](https://lxml.de/apidoc/lxml.objectify.html#lxml.objectify.NumberElement._setValueParser)
        """
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    # Compares .pyval of both operands
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...

# Forget about LongElement, which is only for Python 2.x.
#
# IntElement and FloatElement emulate numeric operations by applying them to the
# .pyval of both operands, so results are plain int, float or complex. They are
# not subclasses of int or float though, and lack all of their non-dunder
# methods and attributes, such as .real or .is_integer(); accessing those
# performs a child element lookup instead.
#
# Operator signatures follow typeshed's int and float, extended to accept number
# elements as the other operand. NumberElement itself implements the same
# operators at runtime, but they only make sense for its concrete subclasses
# (bitwise operators fail on FloatElement).

_PositiveInteger = Literal[
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25,
]  # fmt: skip
_NegativeInteger = Literal[
    -1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16,
    -17, -18, -19, -20,
]  # fmt: skip

class IntElement(NumberElement):
    @property
    def pyval(self) -> int: ...
    def __index__(self) -> int: ...
    @overload
    def __add__(self, other: int | IntElement, /) -> int: ...
    @overload
    def __add__(self, other: float | FloatElement, /) -> float: ...
    @overload
    def __add__(self, other: complex, /) -> complex: ...
    @overload
    def __radd__(self, other: int, /) -> int: ...
    @overload
    def __radd__(self, other: float, /) -> float: ...
    @overload
    def __radd__(self, other: complex, /) -> complex: ...
    @overload
    def __sub__(self, other: int | IntElement, /) -> int: ...
    @overload
    def __sub__(self, other: float | FloatElement, /) -> float: ...
    @overload
    def __sub__(self, other: complex, /) -> complex: ...
    @overload
    def __rsub__(self, other: int, /) -> int: ...
    @overload
    def __rsub__(self, other: float, /) -> float: ...
    @overload
    def __rsub__(self, other: complex, /) -> complex: ...
    @overload
    def __mul__(self, other: int | IntElement, /) -> int: ...
    @overload
    def __mul__(self, other: float | FloatElement, /) -> float: ...
    @overload
    def __mul__(self, other: complex, /) -> complex: ...
    @overload
    def __rmul__(self, other: int, /) -> int: ...
    @overload
    def __rmul__(self, other: float, /) -> float: ...
    @overload
    def __rmul__(self, other: complex, /) -> complex: ...
    @overload
    def __truediv__(self, other: float | IntElement | FloatElement, /) -> float: ...
    @overload
    def __truediv__(self, other: complex, /) -> complex: ...
    @overload
    def __rtruediv__(self, other: float, /) -> float: ...
    @overload
    def __rtruediv__(self, other: complex, /) -> complex: ...
    @overload
    def __floordiv__(self, other: int | IntElement, /) -> int: ...
    @overload
    def __floordiv__(self, other: float | FloatElement, /) -> float: ...
    @overload
    def __rfloordiv__(self, other: int, /) -> int: ...
    @overload
    def __rfloordiv__(self, other: float, /) -> float: ...
    @overload
    def __mod__(self, other: int | IntElement, /) -> int: ...
    @overload
    def __mod__(self, other: float | FloatElement, /) -> float: ...
    @overload
    def __rmod__(self, other: int, /) -> int: ...
    @overload
    def __rmod__(self, other: float, /) -> float: ...
    @overload
    def __divmod__(self, other: int | IntElement, /) -> tuple[int, int]: ...
    @overload
    def __divmod__(self, other: float | FloatElement, /) -> tuple[float, float]: ...
    @overload
    def __rdivmod__(self, other: int, /) -> tuple[int, int]: ...
    @overload
    def __rdivmod__(self, other: float, /) -> tuple[float, float]: ...
    # Modulo is passed to pow() as is, so it can't be an IntElement.
    # This overload comes first so that type checkers use it when
    # matching 3-argument pow() against typeshed's protocol.
    @overload
    def __pow__(self, other: int | IntElement, mod: int, /) -> int: ...
    @overload
    def __pow__(self, other: Literal[0], /) -> Literal[1]: ...
    @overload
    def __pow__(self, other: Literal[0], mod: None, /) -> Literal[1]: ...
    @overload
    def __pow__(self, other: _PositiveInteger, mod: None = None, /) -> int: ...
    @overload
    def __pow__(self, other: _NegativeInteger, mod: None = None, /) -> float: ...
    # int for non-negative exponent, float otherwise
    @overload
    def __pow__(self, other: int | IntElement, mod: None = None, /) -> Any: ...
    # float, or complex for negative base
    @overload
    def __pow__(self, other: float | FloatElement, mod: None = None, /) -> Any: ...
    @overload
    def __pow__(self, other: complex, mod: None = None, /) -> complex: ...
    @overload
    def __rpow__(self, other: int, mod: None = None, /) -> Any: ...
    @overload
    def __rpow__(self, other: float, mod: None = None, /) -> float: ...
    @overload
    def __rpow__(self, other: complex, mod: None = None, /) -> complex: ...
    def __and__(self, other: int | IntElement, /) -> int: ...
    def __rand__(self, other: int, /) -> int: ...
    def __or__(self, other: int | IntElement, /) -> int: ...
    def __ror__(self, other: int, /) -> int: ...
    def __xor__(self, other: int | IntElement, /) -> int: ...
    def __rxor__(self, other: int, /) -> int: ...
    def __lshift__(self, other: int | IntElement, /) -> int: ...
    def __rlshift__(self, other: int, /) -> int: ...
    def __rshift__(self, other: int | IntElement, /) -> int: ...
    def __rrshift__(self, other: int, /) -> int: ...
    def __neg__(self) -> int: ...
    def __pos__(self) -> int: ...
    def __abs__(self) -> int: ...
    def __invert__(self) -> int: ...
    def __lt__(self, other: float | IntElement | FloatElement, /) -> bool: ...
    def __le__(self, other: float | IntElement | FloatElement, /) -> bool: ...
    def __gt__(self, other: float | IntElement | FloatElement, /) -> bool: ...
    def __ge__(self, other: float | IntElement | FloatElement, /) -> bool: ...

class FloatElement(NumberElement):
    @property
    def pyval(self) -> float: ...
    @overload
    def __add__(self, other: float | IntElement | FloatElement, /) -> float: ...
    @overload
    def __add__(self, other: complex, /) -> complex: ...
    @overload
    def __radd__(self, other: float, /) -> float: ...
    @overload
    def __radd__(self, other: complex, /) -> complex: ...
    @overload
    def __sub__(self, other: float | IntElement | FloatElement, /) -> float: ...
    @overload
    def __sub__(self, other: complex, /) -> complex: ...
    @overload
    def __rsub__(self, other: float, /) -> float: ...
    @overload
    def __rsub__(self, other: complex, /) -> complex: ...
    @overload
    def __mul__(self, other: float | IntElement | FloatElement, /) -> float: ...
    @overload
    def __mul__(self, other: complex, /) -> complex: ...
    @overload
    def __rmul__(self, other: float, /) -> float: ...
    @overload
    def __rmul__(self, other: complex, /) -> complex: ...
    @overload
    def __truediv__(self, other: float | IntElement | FloatElement, /) -> float: ...
    @overload
    def __truediv__(self, other: complex, /) -> complex: ...
    @overload
    def __rtruediv__(self, other: float, /) -> float: ...
    @overload
    def __rtruediv__(self, other: complex, /) -> complex: ...
    def __floordiv__(self, other: float | IntElement | FloatElement, /) -> float: ...
    def __rfloordiv__(self, other: float, /) -> float: ...
    def __mod__(self, other: float | IntElement | FloatElement, /) -> float: ...
    def __rmod__(self, other: float, /) -> float: ...
    def __divmod__(
        self, other: float | IntElement | FloatElement, /
    ) -> tuple[float, float]: ...
    # Also accepts IntElement, so that divmod(IntElement, FloatElement)
    # type checks via typeshed's SupportsRDivMod protocol
    def __rdivmod__(self, other: float | IntElement, /) -> tuple[float, float]: ...
    @overload
    def __pow__(self, other: int | IntElement, mod: None = None, /) -> float: ...
    # float, or complex for negative base
    @overload
    def __pow__(self, other: float | FloatElement, mod: None = None, /) -> Any: ...
    @overload
    def __pow__(self, other: complex, mod: None = None, /) -> complex: ...
    @overload
    def __rpow__(self, other: _PositiveInteger, mod: None = None, /) -> float: ...
    @overload
    def __rpow__(self, other: _NegativeInteger, mod: None = None, /) -> complex: ...
    @overload
    def __rpow__(self, other: float, mod: None = None, /) -> Any: ...
    @overload
    def __rpow__(self, other: complex, mod: None = None, /) -> complex: ...
    def __neg__(self) -> float: ...
    def __pos__(self) -> float: ...
    def __abs__(self) -> float: ...
    def __lt__(self, other: float | IntElement | FloatElement, /) -> bool: ...
    def __le__(self, other: float | IntElement | FloatElement, /) -> bool: ...
    def __gt__(self, other: float | IntElement | FloatElement, /) -> bool: ...
    def __ge__(self, other: float | IntElement | FloatElement, /) -> bool: ...

class StringElement(ObjectifiedDataElement):
    """String data class

    Note that this class does *not* support the sequence protocol of strings:
    `len()`, `iter()`, `str_attr[0]`, `str_attr[0:1]`, etc. are *not* supported.
    Instead, use the `.text` attribute to get a 'real' string.
    """

    # For empty string element, .pyval = __str__ = '', .text = None
    @property
    def pyval(self) -> str: ...
    def strlen(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __ge__(self, other: Self | str) -> bool: ...
    def __gt__(self, other: Self | str) -> bool: ...
    def __le__(self, other: Self | str) -> bool: ...
    def __lt__(self, other: Self | str) -> bool: ...
    # Stringify any object before concat
    def __add__(self, other: object) -> str: ...
    def __radd__(self, other: object) -> str: ...
    def __mul__(self, other: SupportsIndex) -> str: ...
    def __rmul__(self, other: SupportsIndex) -> str: ...
    @overload
    def __mod__(
        self, other: LiteralString | tuple[LiteralString, ...]
    ) -> LiteralString: ...
    @overload
    def __mod__(self, other: object) -> str: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __complex__(self) -> complex: ...

class NoneElement(ObjectifiedDataElement):
    @property
    def pyval(self) -> None: ...
    @property  # type: ignore[misc]
    def text(self) -> None: ...
    def __bool__(self) -> Literal[False]: ...

# BoolElement can't inherit from bool, which is marked @final
class BoolElement(IntElement):
    @property
    def pyval(self) -> bool: ...
    @property  # type: ignore[misc]
    def text(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    @overload
    def __and__(self, other: bool | BoolElement, /) -> bool: ...
    @overload
    def __and__(self, other: int | IntElement, /) -> int: ...
    @overload
    def __rand__(self, other: bool, /) -> bool: ...
    @overload
    def __rand__(self, other: int, /) -> int: ...
    @overload
    def __or__(self, other: bool | BoolElement, /) -> bool: ...
    @overload
    def __or__(self, other: int | IntElement, /) -> int: ...
    @overload
    def __ror__(self, other: bool, /) -> bool: ...
    @overload
    def __ror__(self, other: int, /) -> int: ...
    @overload
    def __xor__(self, other: bool | BoolElement, /) -> bool: ...
    @overload
    def __xor__(self, other: int | IntElement, /) -> int: ...
    @overload
    def __rxor__(self, other: bool, /) -> bool: ...
    @overload
    def __rxor__(self, other: int, /) -> int: ...
