from ._types import _AnyStr
from .etree import ElementBase, _FeedParser

class ObjectifiedElement(ElementBase):
    def __getattr__(self, __k: str) -> ObjectifiedElement: ...

def fromstring(
    text: _AnyStr, parser: _FeedParser = ..., *, base_url: _AnyStr = ...
) -> ObjectifiedElement: ...
