name: Formatting

on:
  schedule:
    - cron: '43 6 23 * *'
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Linting and import sort
        uses: chartboost/ruff-action@v1
        with:
          args: 'check --fix'
          src: '.'

      - name: Code formatting
        uses: chartboost/ruff-action@v1
        with:
          args: 'format'
          src: '.'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install tox
        run: pip install --progress-bar=off tox

      - name: Type checker validation on source
        run: >
          tox run-parallel
          --parallel-no-spinner -v
          -e mypy,pyright

      - uses: peter-evans/create-pull-request@v7
        with:
          branch: create-pull-request/formatting
          delete-branch: true
          title: 'Automatic formatting changes'
          commit-message: 'style: automated formatting'
          labels: bot
          sign-commits: true
          body: >
            Automated formatting by
            [ruff-action](https://github.com/ChartBoost/ruff-action) and
            [create-pull-request](https://github.com/peter-evans/create-pull-request)

